/**
 * Design Tokens for Evidence First Brand Guide
 *
 * Generated by Ideaplaces Style Guide Generator
 * Palette: Forensic Teal
 *
 * A cleaner technical palette pairing warm greige neutrals with assertive deep teal and copper editorial highlights.
 */

export const COLORS = {
  // Primary
  primary: '#0F6B6D',
  primaryLight: '#3F8C8D',
  primaryDark: '#0C5658',

  // Secondary
  secondary: '#6E7758',
  secondaryLight: '#8B9276',
  secondaryDark: '#585F46',

  // Accent
  accent: '#C06C3D',

  // Background & Surface
  background: '#F2EFE8',
  backgroundAlt: '#E7E1D7',
  surface: '#FAF8F3',

  // Foreground
  foreground: '#1D2326',
  foregroundMuted: '#707873',

  // Borders
  border: '#CBC4B8',
  borderLight: '#E1DBD1',

  // Semantic
  success: '#5E765B',
  warning: '#B78324',
  error: '#9A6046',
  info: '#0F6B6D',
} as const

export const TYPOGRAPHY = {
  fontFamily: 'Inter, Arial, sans-serif',
  fontFamilyHeading: 'Inter, Arial, sans-serif',
  fontFamilyMono: 'IBM Plex Mono, monospace',
  fontWeightBody: 400,
  fontWeightHeading: 700,
  lineHeightBody: 1.6,
  lineHeightHeading: 1.2,
  scale: [12, 14, 16, 18, 20, 24, 30, 36, 48, 60],
} as const

export const SPACING = {
  baseUnit: 8,
  scale: [4, 8, 12, 16, 24, 32, 48, 64, 96],
  borderRadius: '8px',
  iconStyle: 'outlined',
} as const

export const SHADOWS = {
  sm: '0 1px 2px rgba(0, 0, 0, 0.04)',
  md: '0 2px 4px rgba(0, 0, 0, 0.06)',
  lg: '0 4px 8px rgba(0, 0, 0, 0.08)',
  xl: '0 8px 16px rgba(0, 0, 0, 0.1)',
} as const

export type ColorName = keyof typeof COLORS
